### ISSUE TITLE
Work titles still duplicated on album when grouping tag used.

### ISSUE THREAD

**Issue by daverz** [darrell-k/slimserver#8]
One set of work titles has the grouping tag set and one doesn't.

![Screenshot from 2024-03-05 10-01-55](https://github.com/darrell-k/slimserver/assets/2717422/c1aeacfe-7a8c-4bc6-9740-ba7f143906c2)

Grouping not set:

AccurateRipResult=AccurateRip: Not in database   Secure: Yes   [A34B4D76]
AccurateRipDiscID=006-000dcae9-004973b2-440d8506-1
Title=Dvorak - Symphony No.9 in E Minor, Op.95 'From the New World' - I. Adagio - Allegro Molto
Date=1957
Source=CD (Lossless)
Encoded By=dBpoweramp Release 14.2
Encoder=FLAC 1.2.1
Encoder Settings=-compression-level-5 -verify
ALBUMARTIST=Constantin Silvestri
TRACKNUMBER=1
composer=Dvorak
genre=Symphony
work=Symphony No. 9
worksort=
conductor=Silvestri
artist=
discnumber=15
album=Constantin Silvestri: Complete EMI Recordings
albumsort=Silvestri: Complete EMI Recordings

Grouping set:

AccurateRipResult=AccurateRip: Not in database   Secure: Yes   [A2710976]
AccurateRipDiscID=008-0018c4d8-00a3bab5-70121008-1
Title=Symphony No.9 in E Minor, Op.95 'From the New World' - I. Adagio - Allegro Molto
Source=CD (Lossless)
Encoded By=dBpoweramp Release 14.2
Encoder=FLAC 1.2.1
Encoder Settings=-compression-level-5 -verify
ALBUMARTIST=Constantin Silvestri
TRACKNUMBER=1
composer=Dvorak
genre=Symphony
work=Symphony No. 9
worksort=
conductor=Silvestri
artist=
band=Orchestre National de la Radiodiffusion Francaise
uniquename=Silvestri 1959
discnumber=08
album=Constantin Silvestri: Complete EMI Recordings
albumsort=Silvestri: Complete EMI Recordings
grouping=Silvestri 1959

**Comment by darrell-k** [comment]
Oops! Fix pushed.

**Comment by daverz** [comment]
Yup, it works now.  Thanks!
