### ISSUE TITLE
Blank GROUPING tag results in empty track list.

### ISSUE THREAD

**Issue by daverz** [darrell-k/slimserver#9]
![Screenshot from 2024-03-07 21-35-24](https://github.com/darrell-k/slimserver/assets/2717422/ecada33e-744e-46d6-af27-1eaee047f7ef)

A blank GROUPING tag (tag is defined but no value set) results in an empty track list.

**Comment by darrell-k** [comment]
Finally managed to recreate this using metaflac: my usual tagging software (Kid3 and Puddletag) refused to write zero-length tags at all.

Anyway, presumably we don't want to distinguish between a zero length tag and no tag at all. So I think I should fix this by forcing the tracks.grouping column to NULL in the scan if the grouping tag exists, but has zero length. Do you agree?

**Comment by daverz** [comment]
Sounds fine to me.  

Yes, it's partly a side effect of my metaflac shell script that copied the old UNIQUENAME tag to GROUPING.  I could write another shell script to remove blank GROUPING tags, but if it's easy to handle this case on the LMS end, then seems like a good idea to do so rather than relying on the users' tagging software to do things right.

**Comment by darrell-k** [comment]
We should also treat blank tags (ie length > 0 but all spaces) the same.

**Comment by daverz** [comment]
Yup, if GROUPING='     '  (3 spaces) and GROUPING='' (blank) behaved differently, it would be hard for users to track down the issue.  (Even github strips out my spaces.)

**Comment by darrell-k** [comment]
Fix now pushed. I've also ensured leading/trailing spaces are removed from the imported tag to avoid further confusion.

**Comment by daverz** [comment]
Yup, works great now, thanks.
